services:
  - type: web
    name: fronesis-studio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      PYTHON_VERSION: 3.11.9
